#!/usr/bin/env bash

# install-dev.sh
#
# Run this in any checkout/worktree to set up a local dev environment:
#   - Creates .env with a generated FAMILIA_ADMIN_PASSPHRASE (git-ignored)
#   - Copies Procfile.example -> Procfile for overmind/hivemind
#   - Installs Ruby gems (bundle install)
#   - Installs Node packages (pnpm install)
#   - Builds the Vite SPA (dist/) — the whole frontend the Ruby backend serves
#   - Warns when Valkey/Redis is not reachable on 127.0.0.1:6379
#
# The Vite SPA (src/ -> dist/) is the entire frontend: the Ruby backend serves
# it at /login and, behind the session cookie, at the web root. So this builds
# dist/ and you can open http://127.0.0.1:9292/ directly. For live frontend
# work, `pnpm dev` runs the SPA on Vite's own port (:5173) and proxies
# /admin/api to the Ruby backend on :9292; that path does not need dist/.
#
# (The old Claude Design prototype under resources/01-designs/ is no longer
# served — the SPA replaced it, #23 / T7 — so this script no longer builds it.)
#
# Idempotent: safe to re-run at any time. Never overwrites an existing
# .env, Procfile, or Procfile.dev.

set -euo pipefail

# Generate .env with a random dev passphrase. overmind and hivemind load a
# sibling .env automatically; plain `bundle exec rackup` does not, so export
# it yourself when running the backend by hand.
# Creates the file if missing; leaves it alone if present so local
# customisations survive re-runs.
generate_env() {
    if [[ -f ".env" ]]; then
        if grep -q "FAMILIA_ADMIN_PASSPHRASE" ".env"; then
            echo "OK:   .env already exists"
        else
            echo "Note: .env exists but does not set FAMILIA_ADMIN_PASSPHRASE."
            echo "      Without it the server boots fine but rejects every login"
            echo "      with the generic \"Authentication failed\". Add a line like:"
            echo "        FAMILIA_ADMIN_PASSPHRASE='correct horse battery staple'"
        fi
        return
    fi

    local passphrase
    passphrase="$(ruby -rsecurerandom -e 'puts SecureRandom.hex(16)')"

    cat > ".env" << EOF
# .env — generated by install-dev.sh (git-ignored).
#
# overmind and hivemind load this file automatically. If you run the
# backend by hand, export the variables first:
#   set -a; source .env; set +a; bundle exec rackup
#
# Passphrases shorter than 16 characters (Passphrase::MIN_LENGTH) warn at
# boot in development and refuse to boot in any other environment. Unset
# means every login fails with a generic "Authentication failed" while the
# server otherwise runs.
FAMILIA_ADMIN_PASSPHRASE='${passphrase}'

# If the Ruby backend runs on a port other than 9292, point the Vite
# dev-server proxy at it:
# FAMILIA_ADMIN_BACKEND=http://127.0.0.1:XXXX
EOF
    echo "Created: .env (generated FAMILIA_ADMIN_PASSPHRASE — you'll need it to log in)"
}

# Copy Procfile.example into place for overmind/hivemind. Both Procfile and
# Procfile.dev are git-ignored; respect whichever one already exists.
copy_procfile() {
    if [[ -e "Procfile" ]]; then
        echo "OK:   Procfile already exists"
        return
    fi
    if [[ -e "Procfile.dev" ]]; then
        echo "OK:   Procfile.dev already exists (start with: overmind start -f Procfile.dev)"
        return
    fi
    cp Procfile.example Procfile
    echo "Copy: Procfile.example -> Procfile"
}

# True when something answers on 127.0.0.1:6379. Prefer a real PING (a
# health check, not just an open port); fall back to a bare TCP probe when
# neither CLI is installed.
valkey_reachable() {
    if command -v valkey-cli &>/dev/null; then
        valkey-cli -h 127.0.0.1 -p 6379 ping &>/dev/null
    elif command -v redis-cli &>/dev/null; then
        redis-cli -h 127.0.0.1 -p 6379 ping &>/dev/null
    else
        (exec 3<>/dev/tcp/127.0.0.1/6379) 2>/dev/null
    fi
}

# Sanity check
if [[ ! -f "Gemfile" || ! -f "config.ru" ]]; then
    echo "Error: Run this from a familia-matters checkout root"
    exit 1
fi

# Required tools — fail fast with actionable guidance rather than
# erroring midway through bundle/pnpm install.
missing_required=()
command -v ruby   &>/dev/null || missing_required+=("ruby    (>= 3.2):  https://www.ruby-lang.org/")
command -v bundle &>/dev/null || missing_required+=("bundle  (Ruby Bundler):  https://bundler.io/")
command -v pnpm   &>/dev/null || missing_required+=("pnpm    (Node package manager):  https://pnpm.io/installation")
if (( ${#missing_required[@]} > 0 )); then
    echo "Error: Required tools missing:"
    for tool in "${missing_required[@]}"; do
        echo "  - $tool"
    done
    exit 1
fi

# The Gemfile pins ruby >= 3.2 (the SSE streaming loop relies on
# Queue#pop(timeout:)). Check up front so the failure is this message,
# not a bundler error mid-install.
if ! ruby -e 'exit(Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.2"))'; then
    echo "Error: Ruby >= 3.2 required (found: $(ruby -e 'print RUBY_VERSION'))"
    exit 1
fi

# Check for a process manager (overmind or hivemind) — cache result for
# reuse below. Not required: the two processes can run in two terminals.
has_process_manager=true
if ! command -v overmind &>/dev/null && ! command -v hivemind &>/dev/null; then
    has_process_manager=false
    echo "Warning: neither overmind nor hivemind found — Procfile won't be runnable"
    echo "  Install: https://github.com/DarthSim/overmind#installation"
    echo "  (or run the backend and Vite manually in two terminals; see below)"
    echo ""
fi

generate_env
copy_procfile

echo "---"
echo "Installing Ruby gems..."
bundle install

echo "---"
echo "Installing Node packages..."
pnpm install

echo "---"
echo "Building the Vite SPA (dist/) — the Ruby backend serves it at /login and the web root..."
pnpm build

echo "---"
if valkey_reachable; then
    echo "OK:   Valkey/Redis answering on 127.0.0.1:6379"
else
    echo "Warning: nothing answering on 127.0.0.1:6379"
    echo "  The backend and the try/ suites both need Valkey/Redis there."
    echo "  Start it as a service, or uncomment the valkey line in Procfile"
    echo "  to let the process manager own it."
fi

echo "---"
echo "Setup complete."
echo ""
echo "  The Vite SPA (dist/) was built — the Ruby backend serves it at"
echo "  http://127.0.0.1:9292/ (and /login). For live frontend work, pnpm dev"
echo "  runs it on :5173 and proxies the API to :9292."
echo ""
if [[ "${has_process_manager}" = true ]]; then
    echo "To start (Valkey/Redis on 127.0.0.1:6379 required):"
    echo "  overmind start           # or: hivemind"
else
    echo "Install overmind/hivemind to use the Procfile, or start manually:"
    echo "  set -a; source .env; set +a; bundle exec rackup    # backend on :9292"
    echo "  pnpm dev                                           # Vite on :5173"
fi
echo ""
echo "Then open http://127.0.0.1:9292/ (backend serves the built SPA), or the"
echo "Vite dev URL it prints (default http://localhost:5173/login/) for live"
echo "reload. Log in with the FAMILIA_ADMIN_PASSPHRASE from .env."
echo ""
echo "To test:"
echo "  bundle exec try --agent try/    # Ruby contract suites (needs Valkey/Redis)"
echo "  pnpm test                       # frontend unit tests (vitest)"
